
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auditing?useSSL=false
    username: root
    password: toor
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  flyway:
    baseline-on-migration: true